# Generated by Django 3.1.7 on 2021-03-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210311_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receita',
            old_name='data_receita',
            new_name='date_receita',
        ),
    ]
